### PR TITLE
Add a Gradle build file

### PR DESCRIPTION
**Pull request by jobi**

### CODE REVIEW

**Comment by JakeWharton** [comment]
NineOldAndroids is a jar. You should pull it from Maven central using Gradle's dependency management.

**Comment by kulik** [comment]
Please tell me how i should add maven dependency in build.gradle? 

<code> buildscript {
    repositories {
        maven { url 'http://repo1.maven.org/maven2' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.4'
    }
}
apply plugin: 'android'

dependencies {
    compile 'com.nineoldandroids:library:2.4.0'
}</code>

...
now this is my build script. I am not familiar with gradle, could you help me, how i can add your project in gradle dependency

**Comment by JakeWharton** [comment]
``` groovy
dependencies {
  repositories {
    mavenCentral()
  }

  compile 'com.nineoldandroids:library:2.4.0'
}
```

**Comment by kulik** [comment]
Thank you, I have already resolve my problem. It was not right place for repository. Any way thank you for quick answer.

**Pull request closed without merging**
